### 1. Создание нескольких клиентов со счетами
POST localhost:8080/api/v1/clients
Content-Type: application/json

{
  "first_name": "Имя",
  "last_name": "Фамилия",
  "accounts": [
    {
      "account_num": "123456789",
      "account_type": "card/simple",
      "balance": 5000.00
    },
    {
      "account_num": "987654321",
      "account_type": "card/simple",
      "balance": 10000.00
    }
  ]
}

###
GET localhost:8080/api/v1/clients?client_id=1
Accept: application/json

###
GET localhost:8080/api/v1/clients?client_id=1
Accept: application/xml

### 2. Проведение платежей.
POST localhost:8080/api/v1/payment
Content-Type: application/json

{
  "source_acc_id": 1,
  "dest_acc_id": 2,
  "amount": 100.00,
  "reason": "назначение платежа"
}

###
POST localhost:8080/api/v1/payments
Content-Type: application/json

[
  {
    "source_acc_id": 1,
    "dest_acc_id": 2,
    "amount": 100.00,
    "reason": "назначение платежа"
  },
  {
    "source_acc_id": 2,
    "dest_acc_id": 1,
    "amount": 100000.00,
    "reason": "назначение платежа"
  }
]

### 3. Получение информации по проведенным/забракованным платежам.
POST localhost:8080/api/v1/payments/info
Content-Type: application/json

{
  "payer_id": 1,
  "recipient_id": 1,
  "source_acc_id": 1,
  "dest_acc_id": 2
}